backend:
  name: git-gateway
  branch: main
media_folder: public/cms/
public_folder: "/cms/"
publish_mode: simple
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'beer'
    label: "Beer"
    files:
      - label: 'Beer list'
        name: 'products'
        file: 'public/beer.json'
        create: true
        fields: 
          - {label: "Products", name: "products", widget: "list", fields: [
              {label: "title", name: "title", widget: "string"},
              {label: "product list", name: "productList", widget: "list", fields: [
                {label: "id", name: "id", widget: "string"},
                {label: "quantity", name: "quantity", widget: "string"},
                {label: "title", name: "title", widget: "string"},
                {label: "size", name: "500", widget: "string"},
                {label: "price", name: "price", widget: "string"},
                {label: "image", name: "img", widget: "image"},
                {label: "description", name: "description", widget: "string"}
              ]}
            ]}